{
    'name': 'Inventory Valuation Report | Stock Valuation Report',
    "version": "14.1.1.1",
    'sequence': 1,
    'category': 'Warehouse',
    'summary': 'Using this module you can Get stock report or inventory valuation report in xlsx and pdf formate for any location or warehouse or date range',
    'description': "Using this module you can Get stock report or inventory valuation report in xlsx and pdf formate for any location or warehouse or date range.",
    'price': 22,
    'currency': 'EUR',
    "author" : "ODOOBRIDGE",
    "email": 'support@odoobridge.com',
    "website":'https://odoobridge.com/',
    'license': 'OPL-1',
    # 'depends': ['stock','sale_stock'],
    'depends': ['stock','purchase','sale_stock'],
    'data': [
        'security/ir.model.access.csv',        
        'wizard/daily_sales_report_product_category_wizard.xml',
        'views/report_template_pdf.xml',
        'wizard/inventory_valuation_report_template.xml',
    ],
    'demo': [],
    'test': [],
    'qweb': [],
    # "live_test_url" : "", 
    'images': ['static/description/main_screenshot.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}

